// <auto-generated />
using System;
using Hahn.ApplicatonProcess.July2021.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hahn.ApplicatonProcess.July2021.Data.Migrations
{
    [DbContext(typeof(EFDBContext))]
    [Migration("20211109203118_AmendedEntities2")]
    partial class AmendedEntities2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Base.BaseDomainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseDomainEvent");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Base.BaseDomainEvent", b =>
                {
                    b.HasOne("Hahn.ApplicatonProcess.July2021.Domain.Entities.Asset", null)
                        .WithMany("Events")
                        .HasForeignKey("AssetId");

                    b.HasOne("Hahn.ApplicatonProcess.July2021.Domain.Entities.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Hahn.ApplicatonProcess.July2021.Domain.Entities.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Hahn.ApplicatonProcess.July2021.Domain.Entities.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
